spring.application.name=inventory-service
server.port=8082

# DATABASE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/kafka
spring.datasource.username=postgres
spring.datasource.password=sisu

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== Kafka =====
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

#FIX HERE(allows both order + inventory DTOs)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# optional safety fix (avoids class mismatch)
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.kafka.inventory.model.OrderEvent

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#ignores producer class name mismatch
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Logging
logging.level.org.springframework=INFO
logging.level.com.example.inventoryservice=DEBUG

spring.kafka.listener.ack-mode=manual