spring.application.name=payment-service
server.port=8083

# ================= DATABASE (optional if you use DB) =================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/kafka
spring.datasource.username=postgres
spring.datasource.password=sisu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ================= KAFKA =================
spring.kafka.bootstrap-servers=localhost:9092

# -------- CONSUMER (from inventory-topic) --------
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# IMPORTANT (fix deserialization issues)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# avoid type mismatch issues (VERY IMPORTANT in your case)
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.kafka.payment.model.OrderEvent


# -------- PRODUCER (to payment-topic) --------
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

# ================= LOGGING =================
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=INFO