spring.application.name=notification-service
server.port=8084

# ================= KAFKA =================
spring.kafka.bootstrap-servers=localhost:9092

# -------- CONSUMER (from payment-topic) --------
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# IMPORTANT FIX (avoids ClassNotFound / mapping issues)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# avoid type mismatch issues
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.kafka.notification.model.OrderEvent

# ================= EMAIL (SMTP CONFIG) =================

# java mail propertoies
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=niranjanacharty2013@gmail.com
spring.mail.password=srrq jqki nyae hrch
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# ================= LOGGING =================
logging.level.org.springframework.kafka=INFO
logging.level.org.springframework.mail=INFO